/* synapse-main.c generated by valac 0.28.1, the Vala compiler
 * generated from synapse-main.vala, do not modify */

/*
 * Copyright (C) 2010 Michal Hruby <michal.mhr@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by Alberto Aldegheri <albyrock87+dev@gmail.com>
 *             Michal Hruby <michal.mhr@gmail.com>
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <synapse-core.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <keybinder.h>
#include <glib/gi18n-lib.h>
#include <plugins.h>
#include <glib/gstdio.h>
#include <locale.h>
#include "config.h"
#include <libnotify/notify.h>
#include <gio/gio.h>


#define SYNAPSE_TYPE_UI_LAUNCHER (synapse_ui_launcher_get_type ())
#define SYNAPSE_UI_LAUNCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_TYPE_UI_LAUNCHER, SynapseUILauncher))
#define SYNAPSE_UI_LAUNCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_TYPE_UI_LAUNCHER, SynapseUILauncherClass))
#define SYNAPSE_IS_UI_LAUNCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_TYPE_UI_LAUNCHER))
#define SYNAPSE_IS_UI_LAUNCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_TYPE_UI_LAUNCHER))
#define SYNAPSE_UI_LAUNCHER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_TYPE_UI_LAUNCHER, SynapseUILauncherClass))

typedef struct _SynapseUILauncher SynapseUILauncher;
typedef struct _SynapseUILauncherClass SynapseUILauncherClass;
typedef struct _SynapseUILauncherPrivate SynapseUILauncherPrivate;

#define SYNAPSE_GUI_TYPE_SETTINGS_WINDOW (synapse_gui_settings_window_get_type ())
#define SYNAPSE_GUI_SETTINGS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_SETTINGS_WINDOW, SynapseGuiSettingsWindow))
#define SYNAPSE_GUI_SETTINGS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_SETTINGS_WINDOW, SynapseGuiSettingsWindowClass))
#define SYNAPSE_GUI_IS_SETTINGS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_SETTINGS_WINDOW))
#define SYNAPSE_GUI_IS_SETTINGS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_SETTINGS_WINDOW))
#define SYNAPSE_GUI_SETTINGS_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_SETTINGS_WINDOW, SynapseGuiSettingsWindowClass))

typedef struct _SynapseGuiSettingsWindow SynapseGuiSettingsWindow;
typedef struct _SynapseGuiSettingsWindowClass SynapseGuiSettingsWindowClass;

#define SYNAPSE_GUI_TYPE_KEY_COMBO_CONFIG (synapse_gui_key_combo_config_get_type ())
#define SYNAPSE_GUI_KEY_COMBO_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_KEY_COMBO_CONFIG, SynapseGuiKeyComboConfig))
#define SYNAPSE_GUI_KEY_COMBO_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_KEY_COMBO_CONFIG, SynapseGuiKeyComboConfigClass))
#define SYNAPSE_GUI_IS_KEY_COMBO_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_KEY_COMBO_CONFIG))
#define SYNAPSE_GUI_IS_KEY_COMBO_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_KEY_COMBO_CONFIG))
#define SYNAPSE_GUI_KEY_COMBO_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_KEY_COMBO_CONFIG, SynapseGuiKeyComboConfigClass))

typedef struct _SynapseGuiKeyComboConfig SynapseGuiKeyComboConfig;
typedef struct _SynapseGuiKeyComboConfigClass SynapseGuiKeyComboConfigClass;

#define SYNAPSE_GUI_TYPE_CATEGORY_CONFIG (synapse_gui_category_config_get_type ())
#define SYNAPSE_GUI_CATEGORY_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_CATEGORY_CONFIG, SynapseGuiCategoryConfig))
#define SYNAPSE_GUI_CATEGORY_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_CATEGORY_CONFIG, SynapseGuiCategoryConfigClass))
#define SYNAPSE_GUI_IS_CATEGORY_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_CATEGORY_CONFIG))
#define SYNAPSE_GUI_IS_CATEGORY_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_CATEGORY_CONFIG))
#define SYNAPSE_GUI_CATEGORY_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_CATEGORY_CONFIG, SynapseGuiCategoryConfigClass))

typedef struct _SynapseGuiCategoryConfig SynapseGuiCategoryConfig;
typedef struct _SynapseGuiCategoryConfigClass SynapseGuiCategoryConfigClass;

#define SYNAPSE_GUI_TYPE_ICONTROLLER (synapse_gui_icontroller_get_type ())
#define SYNAPSE_GUI_ICONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_ICONTROLLER, SynapseGuiIController))
#define SYNAPSE_GUI_IS_ICONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_ICONTROLLER))
#define SYNAPSE_GUI_ICONTROLLER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYNAPSE_GUI_TYPE_ICONTROLLER, SynapseGuiIControllerIface))

typedef struct _SynapseGuiIController SynapseGuiIController;
typedef struct _SynapseGuiIControllerIface SynapseGuiIControllerIface;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define SYNAPSE_GUI_TYPE_CONTROLLER (synapse_gui_controller_get_type ())
#define SYNAPSE_GUI_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_GUI_TYPE_CONTROLLER, SynapseGuiController))
#define SYNAPSE_GUI_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_GUI_TYPE_CONTROLLER, SynapseGuiControllerClass))
#define SYNAPSE_GUI_IS_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_GUI_TYPE_CONTROLLER))
#define SYNAPSE_GUI_IS_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_GUI_TYPE_CONTROLLER))
#define SYNAPSE_GUI_CONTROLLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_GUI_TYPE_CONTROLLER, SynapseGuiControllerClass))

typedef struct _SynapseGuiController SynapseGuiController;
typedef struct _SynapseGuiControllerClass SynapseGuiControllerClass;
typedef struct _Block1Data Block1Data;
typedef struct _Block2Data Block2Data;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_option_context_free0(var) ((var == NULL) ? NULL : (var = (g_option_context_free (var), NULL)))

struct _SynapseUILauncher {
	GObject parent_instance;
	SynapseUILauncherPrivate * priv;
};

struct _SynapseUILauncherClass {
	GObjectClass parent_class;
};

struct _SynapseGuiIControllerIface {
	GTypeInterface parent_iface;
	void (*key_press_event) (SynapseGuiIController* self, GdkEventKey* event);
	void (*category_changed_event) (SynapseGuiIController* self, gint category_index);
	void (*fire_focus_context_switch_event) (SynapseGuiIController* self);
	void (*fire_focus) (SynapseGuiIController* self);
	void (*selected_index_changed_event) (SynapseGuiIController* self, gint focus_index);
	void (*set_view) (SynapseGuiIController* self, GType view_type);
	void (*summon_or_vanish) (SynapseGuiIController* self);
	gboolean (*is_in_initial_state) (SynapseGuiIController* self);
	gboolean (*searched_for_recent) (SynapseGuiIController* self);
	SynapseDataSink* (*get_data_sink) (SynapseGuiIController* self);
	void (*set_data_sink) (SynapseGuiIController* self, SynapseDataSink* value);
	SynapseGuiKeyComboConfig* (*get_key_combo_config) (SynapseGuiIController* self);
	void (*set_key_combo_config) (SynapseGuiIController* self, SynapseGuiKeyComboConfig* value);
	SynapseGuiCategoryConfig* (*get_category_config) (SynapseGuiIController* self);
	void (*set_category_config) (SynapseGuiIController* self, SynapseGuiCategoryConfig* value);
};

struct _SynapseUILauncherPrivate {
	SynapseGuiSettingsWindow* settings;
	SynapseDataSink* data_sink;
	SynapseGuiKeyComboConfig* key_combo_config;
	SynapseGuiCategoryConfig* category_config;
	gchar* current_shortcut;
	SynapseConfigService* config;
	GtkStatusIcon* status_icon;
	SynapseGuiIController* controller;
};

struct _Block1Data {
	int _ref_count_;
	SynapseUILauncher* self;
	GtkMenu* indicator_menu;
};

struct _Block2Data {
	int _ref_count_;
	SynapseUILauncher* launcher;
};


static gpointer synapse_ui_launcher_parent_class = NULL;
static gboolean synapse_ui_launcher_is_startup;
static gboolean synapse_ui_launcher_is_startup = FALSE;

GType synapse_ui_launcher_get_type (void) G_GNUC_CONST;
GType synapse_gui_settings_window_get_type (void) G_GNUC_CONST;
GType synapse_gui_key_combo_config_get_type (void) G_GNUC_CONST;
GType synapse_gui_category_config_get_type (void) G_GNUC_CONST;
GType synapse_gui_icontroller_get_type (void) G_GNUC_CONST;
#define SYNAPSE_UI_LAUNCHER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYNAPSE_TYPE_UI_LAUNCHER, SynapseUILauncherPrivate))
enum  {
	SYNAPSE_UI_LAUNCHER_DUMMY_PROPERTY
};
SynapseUILauncher* synapse_ui_launcher_new (void);
SynapseUILauncher* synapse_ui_launcher_construct (GType object_type);
void synapse_gui_key_combo_config_update_bindings (SynapseGuiKeyComboConfig* self);
static void synapse_ui_launcher_register_plugins (SynapseUILauncher* self);
SynapseGuiSettingsWindow* synapse_gui_settings_window_new (SynapseDataSink* data_sink, SynapseGuiKeyComboConfig* key_combo_config);
SynapseGuiSettingsWindow* synapse_gui_settings_window_construct (GType object_type, SynapseDataSink* data_sink, SynapseGuiKeyComboConfig* key_combo_config);
static void synapse_ui_launcher_change_keyboard_shortcut (SynapseUILauncher* self, const gchar* key);
static void _synapse_ui_launcher_change_keyboard_shortcut_synapse_gui_settings_window_keybinding_changed (SynapseGuiSettingsWindow* _sender, const gchar* keybinding, gpointer self);
static void synapse_ui_launcher_bind_keyboard_shortcut (SynapseUILauncher* self);
GType synapse_gui_controller_get_type (void) G_GNUC_CONST;
static void __lambda39_ (SynapseUILauncher* self);
void synapse_gui_icontroller_summon_or_vanish (SynapseGuiIController* self);
static void ___lambda39__synapse_gui_icontroller_show_settings_requested (SynapseGuiIController* _sender, gpointer self);
static void synapse_ui_launcher_init_ui (SynapseUILauncher* self, GType t);
GType synapse_gui_settings_window_get_current_theme (SynapseGuiSettingsWindow* self);
static void _synapse_ui_launcher_init_ui_synapse_gui_settings_window_theme_selected (SynapseGuiSettingsWindow* _sender, GType theme, gpointer self);
static void synapse_ui_launcher_init_indicator (SynapseUILauncher* self);
void synapse_gui_icontroller_set_view (SynapseGuiIController* self, GType view_type);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void __lambda40_ (SynapseUILauncher* self);
void synapse_ui_launcher_show_ui (SynapseUILauncher* self);
static void ___lambda40__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
static void __lambda41_ (SynapseUILauncher* self);
static void ___lambda41__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
static void _gtk_main_quit_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
static void __lambda42_ (Block1Data* _data1_, GtkStatusIcon* icon, guint button, guint event_time);
static void _gtk_status_icon_position_menu_gtk_menu_position_func (GtkMenu* menu, gint* x, gint* y, gboolean* push_in, gpointer self);
static void ___lambda42__gtk_status_icon_popup_menu (GtkStatusIcon* _sender, guint button, guint activate_time, gpointer self);
static void __lambda43_ (SynapseUILauncher* self);
static void ___lambda43__gtk_status_icon_activate (GtkStatusIcon* _sender, gpointer self);
gboolean synapse_gui_settings_window_get_indicator_active (SynapseGuiSettingsWindow* self);
static void __lambda44_ (SynapseUILauncher* self);
static void ___lambda44__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
const gchar* synapse_gui_key_combo_config_get_activate (SynapseGuiKeyComboConfig* self);
void synapse_gui_settings_window_set_keybinding (SynapseGuiSettingsWindow* self, const gchar* key, gboolean emit);
static void synapse_ui_launcher_handle_shortcut (const gchar* key, void* data);
static void _synapse_ui_launcher_handle_shortcut_keybinder_handler (const gchar* keystring, void* udata);
void synapse_ui_launcher_run (SynapseUILauncher* self);
static void synapse_ui_launcher_load_custom_style (void);
static void synapse_ui_launcher_ibus_fix (void);
gint synapse_ui_launcher_main (gchar** argv, int argv_length1);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static void ____lambda45_ (Block2Data* _data2_);
static void _____lambda45__g_application_activate (GApplication* _sender, gpointer self);
static void synapse_ui_launcher_finalize (GObject* obj);

static const GOptionEntry SYNAPSE_UI_LAUNCHER_options[2] = {{"startup", 's', 0, G_OPTION_ARG_NONE, &synapse_ui_launcher_is_startup, "Startup mode (hide the UI until activated).", ""}, {NULL}};

static void _synapse_ui_launcher_change_keyboard_shortcut_synapse_gui_settings_window_keybinding_changed (SynapseGuiSettingsWindow* _sender, const gchar* keybinding, gpointer self) {
#line 64 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_ui_launcher_change_keyboard_shortcut ((SynapseUILauncher*) self, keybinding);
#line 225 "synapse-main.c"
}


static void __lambda39_ (SynapseUILauncher* self) {
	SynapseGuiSettingsWindow* _tmp0_ = NULL;
	guint32 timestamp = 0U;
	guint32 _tmp1_ = 0U;
	SynapseGuiSettingsWindow* _tmp2_ = NULL;
	SynapseGuiSettingsWindow* _tmp3_ = NULL;
	SynapseGuiSettingsWindow* _tmp4_ = NULL;
	GdkWindow* _tmp5_ = NULL;
	SynapseGuiSettingsWindow* _tmp6_ = NULL;
	GdkWindow* _tmp7_ = NULL;
	SynapseGuiIController* _tmp8_ = NULL;
#line 75 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_ = self->priv->settings;
#line 75 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gtk_widget_show ((GtkWidget*) _tmp0_);
#line 76 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp1_ = gtk_get_current_event_time ();
#line 76 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	timestamp = _tmp1_;
#line 78 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp2_ = self->priv->settings;
#line 78 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gtk_window_deiconify ((GtkWindow*) _tmp2_);
#line 79 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp3_ = self->priv->settings;
#line 79 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gtk_window_present_with_time ((GtkWindow*) _tmp3_, timestamp);
#line 80 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp4_ = self->priv->settings;
#line 80 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp5_ = gtk_widget_get_window ((GtkWidget*) _tmp4_);
#line 80 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gdk_window_raise (_tmp5_);
#line 81 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp6_ = self->priv->settings;
#line 81 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp7_ = gtk_widget_get_window ((GtkWidget*) _tmp6_);
#line 81 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gdk_window_focus (_tmp7_, timestamp);
#line 82 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp8_ = self->priv->controller;
#line 82 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_gui_icontroller_summon_or_vanish (_tmp8_);
#line 272 "synapse-main.c"
}


static void ___lambda39__synapse_gui_icontroller_show_settings_requested (SynapseGuiIController* _sender, gpointer self) {
#line 74 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	__lambda39_ ((SynapseUILauncher*) self);
#line 279 "synapse-main.c"
}


static void _synapse_ui_launcher_init_ui_synapse_gui_settings_window_theme_selected (SynapseGuiSettingsWindow* _sender, GType theme, gpointer self) {
#line 89 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_ui_launcher_init_ui ((SynapseUILauncher*) self, theme);
#line 286 "synapse-main.c"
}


SynapseUILauncher* synapse_ui_launcher_construct (GType object_type) {
	SynapseUILauncher * self = NULL;
	SynapseConfigService* _tmp0_ = NULL;
	SynapseDataSink* _tmp1_ = NULL;
	SynapseConfigService* _tmp2_ = NULL;
	SynapseConfigObject* _tmp3_ = NULL;
	SynapseConfigService* _tmp4_ = NULL;
	SynapseConfigObject* _tmp5_ = NULL;
	SynapseGuiKeyComboConfig* _tmp6_ = NULL;
	SynapseDataSink* _tmp7_ = NULL;
	SynapseGuiKeyComboConfig* _tmp8_ = NULL;
	SynapseGuiSettingsWindow* _tmp9_ = NULL;
	SynapseGuiSettingsWindow* _tmp10_ = NULL;
	SynapseDataSink* _tmp11_ = NULL;
	SynapseGuiKeyComboConfig* _tmp12_ = NULL;
	SynapseGuiCategoryConfig* _tmp13_ = NULL;
	GObject* _tmp14_ = NULL;
	GObject* _tmp15_ = NULL;
	SynapseGuiIController* _tmp16_ = NULL;
	SynapseGuiIController* _tmp17_ = NULL;
	SynapseGuiSettingsWindow* _tmp18_ = NULL;
	GType _tmp19_ = 0UL;
	gboolean _tmp20_ = FALSE;
	SynapseGuiSettingsWindow* _tmp22_ = NULL;
#line 55 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	self = (SynapseUILauncher*) g_object_new (object_type, NULL);
#line 57 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_ = synapse_config_service_get_default ();
#line 57 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (self->priv->config);
#line 57 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	self->priv->config = _tmp0_;
#line 58 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp1_ = synapse_data_sink_new ();
#line 58 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (self->priv->data_sink);
#line 58 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	self->priv->data_sink = _tmp1_;
#line 59 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp2_ = self->priv->config;
#line 59 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp3_ = synapse_config_service_bind_config (_tmp2_, "ui", "shortcuts", SYNAPSE_GUI_TYPE_KEY_COMBO_CONFIG);
#line 59 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (self->priv->key_combo_config);
#line 59 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	self->priv->key_combo_config = G_TYPE_CHECK_INSTANCE_CAST (_tmp3_, SYNAPSE_GUI_TYPE_KEY_COMBO_CONFIG, SynapseGuiKeyComboConfig);
#line 60 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp4_ = self->priv->config;
#line 60 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp5_ = synapse_config_service_get_config (_tmp4_, "ui", "categories", SYNAPSE_GUI_TYPE_CATEGORY_CONFIG);
#line 60 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (self->priv->category_config);
#line 60 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	self->priv->category_config = G_TYPE_CHECK_INSTANCE_CAST (_tmp5_, SYNAPSE_GUI_TYPE_CATEGORY_CONFIG, SynapseGuiCategoryConfig);
#line 61 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp6_ = self->priv->key_combo_config;
#line 61 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_gui_key_combo_config_update_bindings (_tmp6_);
#line 62 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_ui_launcher_register_plugins (self);
#line 63 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp7_ = self->priv->data_sink;
#line 63 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp8_ = self->priv->key_combo_config;
#line 63 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp9_ = synapse_gui_settings_window_new (_tmp7_, _tmp8_);
#line 63 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_object_ref_sink (_tmp9_);
#line 63 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (self->priv->settings);
#line 63 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	self->priv->settings = _tmp9_;
#line 64 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp10_ = self->priv->settings;
#line 64 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_signal_connect_object (_tmp10_, "keybinding-changed", (GCallback) _synapse_ui_launcher_change_keyboard_shortcut_synapse_gui_settings_window_keybinding_changed, self, 0);
#line 66 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	keybinder_init ();
#line 67 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_ui_launcher_bind_keyboard_shortcut (self);
#line 69 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp11_ = self->priv->data_sink;
#line 69 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp12_ = self->priv->key_combo_config;
#line 69 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp13_ = self->priv->category_config;
#line 69 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp14_ = g_object_new (SYNAPSE_GUI_TYPE_CONTROLLER, "data-sink", _tmp11_, "key-combo-config", _tmp12_, "category-config", _tmp13_, NULL);
#line 69 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp15_ = G_IS_INITIALLY_UNOWNED (_tmp14_) ? g_object_ref_sink (_tmp14_) : _tmp14_;
#line 69 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp16_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp15_, SYNAPSE_GUI_TYPE_ICONTROLLER) ? ((SynapseGuiIController*) _tmp15_) : NULL;
#line 69 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	if (_tmp16_ == NULL) {
#line 69 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_g_object_unref0 (_tmp15_);
#line 386 "synapse-main.c"
	}
#line 69 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (self->priv->controller);
#line 69 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	self->priv->controller = _tmp16_;
#line 74 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp17_ = self->priv->controller;
#line 74 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_signal_connect_object (_tmp17_, "show-settings-requested", (GCallback) ___lambda39__synapse_gui_icontroller_show_settings_requested, self, 0);
#line 85 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp18_ = self->priv->settings;
#line 85 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp19_ = synapse_gui_settings_window_get_current_theme (_tmp18_);
#line 85 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_ui_launcher_init_ui (self, _tmp19_);
#line 87 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp20_ = synapse_ui_launcher_is_startup;
#line 87 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	if (!_tmp20_) {
#line 406 "synapse-main.c"
		SynapseGuiIController* _tmp21_ = NULL;
#line 87 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_tmp21_ = self->priv->controller;
#line 87 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		synapse_gui_icontroller_summon_or_vanish (_tmp21_);
#line 412 "synapse-main.c"
	}
#line 89 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp22_ = self->priv->settings;
#line 89 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_signal_connect_object (_tmp22_, "theme-selected", (GCallback) _synapse_ui_launcher_init_ui_synapse_gui_settings_window_theme_selected, self, 0);
#line 90 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_ui_launcher_init_indicator (self);
#line 69 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	return self;
#line 422 "synapse-main.c"
}


SynapseUILauncher* synapse_ui_launcher_new (void) {
#line 55 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	return synapse_ui_launcher_construct (SYNAPSE_TYPE_UI_LAUNCHER);
#line 429 "synapse-main.c"
}


static void synapse_ui_launcher_init_ui (SynapseUILauncher* self, GType t) {
	SynapseGuiIController* _tmp0_ = NULL;
	GType _tmp1_ = 0UL;
#line 93 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_return_if_fail (self != NULL);
#line 95 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_ = self->priv->controller;
#line 95 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp1_ = t;
#line 95 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_gui_icontroller_set_view (_tmp0_, _tmp1_);
#line 444 "synapse-main.c"
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	return _data1_;
#line 453 "synapse-main.c"
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 462 "synapse-main.c"
		SynapseUILauncher* self;
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		self = _data1_->self;
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_g_object_unref0 (_data1_->indicator_menu);
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_g_object_unref0 (self);
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		g_slice_free (Block1Data, _data1_);
#line 472 "synapse-main.c"
	}
}


static void __lambda40_ (SynapseUILauncher* self) {
#line 109 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_ui_launcher_show_ui (self);
#line 480 "synapse-main.c"
}


static void ___lambda40__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
#line 108 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	__lambda40_ ((SynapseUILauncher*) self);
#line 487 "synapse-main.c"
}


static void __lambda41_ (SynapseUILauncher* self) {
	SynapseGuiSettingsWindow* _tmp0_ = NULL;
#line 114 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_ = self->priv->settings;
#line 114 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gtk_widget_show ((GtkWidget*) _tmp0_);
#line 497 "synapse-main.c"
}


static void ___lambda41__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
#line 113 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	__lambda41_ ((SynapseUILauncher*) self);
#line 504 "synapse-main.c"
}


static void _gtk_main_quit_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
#line 119 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gtk_main_quit ();
#line 511 "synapse-main.c"
}


static void _gtk_status_icon_position_menu_gtk_menu_position_func (GtkMenu* menu, gint* x, gint* y, gboolean* push_in, gpointer self) {
#line 140 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gtk_status_icon_position_menu (menu, x, y, push_in, (GtkStatusIcon*) self);
#line 518 "synapse-main.c"
}


static void __lambda42_ (Block1Data* _data1_, GtkStatusIcon* icon, guint button, guint event_time) {
	SynapseUILauncher* self;
	GtkStatusIcon* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	guint _tmp2_ = 0U;
#line 139 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	self = _data1_->self;
#line 139 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_return_if_fail (icon != NULL);
#line 140 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_ = self->priv->status_icon;
#line 140 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp1_ = button;
#line 140 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp2_ = event_time;
#line 140 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gtk_menu_popup (_data1_->indicator_menu, NULL, NULL, _gtk_status_icon_position_menu_gtk_menu_position_func, _tmp0_, _tmp1_, (guint32) _tmp2_);
#line 539 "synapse-main.c"
}


static void ___lambda42__gtk_status_icon_popup_menu (GtkStatusIcon* _sender, guint button, guint activate_time, gpointer self) {
#line 139 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	__lambda42_ (self, _sender, button, activate_time);
#line 546 "synapse-main.c"
}


static void __lambda43_ (SynapseUILauncher* self) {
#line 143 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_ui_launcher_show_ui (self);
#line 553 "synapse-main.c"
}


static void ___lambda43__gtk_status_icon_activate (GtkStatusIcon* _sender, gpointer self) {
#line 142 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	__lambda43_ ((SynapseUILauncher*) self);
#line 560 "synapse-main.c"
}


static void __lambda44_ (SynapseUILauncher* self) {
	GtkStatusIcon* _tmp0_ = NULL;
	SynapseGuiSettingsWindow* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
#line 148 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_ = self->priv->status_icon;
#line 148 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp1_ = self->priv->settings;
#line 148 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp2_ = synapse_gui_settings_window_get_indicator_active (_tmp1_);
#line 148 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp3_ = _tmp2_;
#line 148 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gtk_status_icon_set_visible (_tmp0_, _tmp3_);
#line 579 "synapse-main.c"
}


static void ___lambda44__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 147 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	__lambda44_ ((SynapseUILauncher*) self);
#line 586 "synapse-main.c"
}


static void synapse_ui_launcher_init_indicator (SynapseUILauncher* self) {
	Block1Data* _data1_;
	GtkMenu* _tmp0_ = NULL;
	GtkImageMenuItem* activate_item = NULL;
	const gchar* _tmp1_ = NULL;
	GtkImageMenuItem* _tmp2_ = NULL;
	GtkImage* _tmp3_ = NULL;
	GtkImage* _tmp4_ = NULL;
	GtkImageMenuItem* settings_item = NULL;
	GtkImageMenuItem* _tmp5_ = NULL;
	GtkSeparatorMenuItem* _tmp6_ = NULL;
	GtkSeparatorMenuItem* _tmp7_ = NULL;
	GtkImageMenuItem* quit_item = NULL;
	GtkImageMenuItem* _tmp8_ = NULL;
	GtkStatusIcon* _tmp9_ = NULL;
	GtkStatusIcon* _tmp10_ = NULL;
	GtkStatusIcon* _tmp11_ = NULL;
	GtkStatusIcon* _tmp12_ = NULL;
	SynapseGuiSettingsWindow* _tmp13_ = NULL;
	gboolean _tmp14_ = FALSE;
	gboolean _tmp15_ = FALSE;
	SynapseGuiSettingsWindow* _tmp16_ = NULL;
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_return_if_fail (self != NULL);
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_data1_ = g_slice_new0 (Block1Data);
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_data1_->_ref_count_ = 1;
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_data1_->self = g_object_ref (self);
#line 105 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_ = (GtkMenu*) gtk_menu_new ();
#line 105 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_object_ref_sink (_tmp0_);
#line 105 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_data1_->indicator_menu = _tmp0_;
#line 106 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp1_ = _ ("Activate");
#line 106 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp2_ = (GtkImageMenuItem*) gtk_image_menu_item_new_with_label (_tmp1_);
#line 106 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_object_ref_sink (_tmp2_);
#line 106 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	activate_item = _tmp2_;
#line 107 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp3_ = (GtkImage*) gtk_image_new_from_stock (GTK_STOCK_EXECUTE, GTK_ICON_SIZE_MENU);
#line 107 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_object_ref_sink (_tmp3_);
#line 107 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp4_ = _tmp3_;
#line 107 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gtk_image_menu_item_set_image (activate_item, (GtkWidget*) _tmp4_);
#line 107 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (_tmp4_);
#line 108 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_signal_connect_object ((GtkMenuItem*) activate_item, "activate", (GCallback) ___lambda40__gtk_menu_item_activate, self, 0);
#line 111 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gtk_menu_shell_append ((GtkMenuShell*) _data1_->indicator_menu, (GtkWidget*) ((GtkMenuItem*) activate_item));
#line 112 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp5_ = (GtkImageMenuItem*) gtk_image_menu_item_new_from_stock (GTK_STOCK_PREFERENCES, NULL);
#line 112 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_object_ref_sink (_tmp5_);
#line 112 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	settings_item = _tmp5_;
#line 113 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_signal_connect_object ((GtkMenuItem*) settings_item, "activate", (GCallback) ___lambda41__gtk_menu_item_activate, self, 0);
#line 116 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gtk_menu_shell_append ((GtkMenuShell*) _data1_->indicator_menu, (GtkWidget*) ((GtkMenuItem*) settings_item));
#line 117 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp6_ = (GtkSeparatorMenuItem*) gtk_separator_menu_item_new ();
#line 117 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_object_ref_sink (_tmp6_);
#line 117 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp7_ = _tmp6_;
#line 117 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gtk_menu_shell_append ((GtkMenuShell*) _data1_->indicator_menu, (GtkWidget*) ((GtkMenuItem*) _tmp7_));
#line 117 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (_tmp7_);
#line 118 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp8_ = (GtkImageMenuItem*) gtk_image_menu_item_new_from_stock (GTK_STOCK_QUIT, NULL);
#line 118 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_object_ref_sink (_tmp8_);
#line 118 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	quit_item = _tmp8_;
#line 119 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_signal_connect ((GtkMenuItem*) quit_item, "activate", (GCallback) _gtk_main_quit_gtk_menu_item_activate, NULL);
#line 120 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gtk_menu_shell_append ((GtkMenuShell*) _data1_->indicator_menu, (GtkWidget*) ((GtkMenuItem*) quit_item));
#line 121 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gtk_widget_show_all ((GtkWidget*) _data1_->indicator_menu);
#line 137 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp9_ = gtk_status_icon_new_from_icon_name ("synapse");
#line 137 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (self->priv->status_icon);
#line 137 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	self->priv->status_icon = _tmp9_;
#line 139 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp10_ = self->priv->status_icon;
#line 139 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_signal_connect_data (_tmp10_, "popup-menu", (GCallback) ___lambda42__gtk_status_icon_popup_menu, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 142 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp11_ = self->priv->status_icon;
#line 142 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_signal_connect_object (_tmp11_, "activate", (GCallback) ___lambda43__gtk_status_icon_activate, self, 0);
#line 145 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp12_ = self->priv->status_icon;
#line 145 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp13_ = self->priv->settings;
#line 145 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp14_ = synapse_gui_settings_window_get_indicator_active (_tmp13_);
#line 145 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp15_ = _tmp14_;
#line 145 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gtk_status_icon_set_visible (_tmp12_, _tmp15_);
#line 147 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp16_ = self->priv->settings;
#line 147 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_signal_connect_object ((GObject*) _tmp16_, "notify::indicator-active", (GCallback) ___lambda44__g_object_notify, self, 0);
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (quit_item);
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (settings_item);
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (activate_item);
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	block1_data_unref (_data1_);
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_data1_ = NULL;
#line 718 "synapse-main.c"
}


static void synapse_ui_launcher_register_plugins (SynapseUILauncher* self) {
	GType* plugin_types = NULL;
	GType* _tmp0_ = NULL;
	gint plugin_types_length1 = 0;
	gint _plugin_types_size_ = 0;
	GType* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
#line 153 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_return_if_fail (self != NULL);
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_ = g_new0 (GType, 27);
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[0] = SYNAPSE_TYPE_DESKTOP_FILE_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[1] = SYNAPSE_TYPE_HYBRID_SEARCH_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[2] = SYNAPSE_TYPE_GNOME_BOOKMARKS_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[3] = SYNAPSE_TYPE_GNOME_SESSION_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[4] = SYNAPSE_TYPE_GNOME_SCREEN_SAVER_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[5] = SYNAPSE_TYPE_SYSTEM_MANAGEMENT_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[6] = SYNAPSE_TYPE_COMMAND_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[7] = SYNAPSE_TYPE_RHYTHMBOX_ACTIONS;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[8] = SYNAPSE_TYPE_BANSHEE_ACTIONS;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[9] = SYNAPSE_TYPE_DIRECTORY_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[10] = SYNAPSE_TYPE_LAUNCHPAD_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[11] = SYNAPSE_TYPE_CALCULATOR_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[12] = SYNAPSE_TYPE_SELECTION_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[13] = SYNAPSE_TYPE_SSH_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[14] = SYNAPSE_TYPE_XNOISE_ACTIONS;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[15] = SYNAPSE_TYPE_CHROMIUM_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[16] = SYNAPSE_TYPE_FILE_OP_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[17] = SYNAPSE_TYPE_PIDGIN_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[18] = SYNAPSE_TYPE_CHAT_ACTIONS;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[19] = SYNAPSE_TYPE_ZEAL_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[20] = SYNAPSE_TYPE_ZEITGEIST_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[21] = SYNAPSE_TYPE_ZEITGEIST_RELATED;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[22] = SYNAPSE_TYPE_DEVHELP_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[23] = SYNAPSE_TYPE_OPEN_SEARCH_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[24] = SYNAPSE_TYPE_LOCATE_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[25] = SYNAPSE_TYPE_PASTEBIN_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_[26] = SYNAPSE_TYPE_DICTIONARY_PLUGIN;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	plugin_types = _tmp0_;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	plugin_types_length1 = 27;
#line 156 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_plugin_types_size_ = plugin_types_length1;
#line 197 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp1_ = plugin_types;
#line 197 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp1__length1 = plugin_types_length1;
#line 797 "synapse-main.c"
	{
		GType* t_collection = NULL;
		gint t_collection_length1 = 0;
		gint _t_collection_size_ = 0;
		gint t_it = 0;
#line 197 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		t_collection = _tmp1_;
#line 197 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		t_collection_length1 = _tmp1__length1;
#line 197 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		for (t_it = 0; t_it < _tmp1__length1; t_it = t_it + 1) {
#line 809 "synapse-main.c"
			GType t = 0UL;
#line 197 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			t = t_collection[t_it];
#line 813 "synapse-main.c"
			{
				SynapseDataSink* _tmp2_ = NULL;
				GType _tmp3_ = 0UL;
#line 199 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
				_tmp2_ = self->priv->data_sink;
#line 199 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
				_tmp3_ = t;
#line 199 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
				synapse_data_sink_register_static_plugin (_tmp2_, _tmp3_);
#line 823 "synapse-main.c"
			}
		}
	}
#line 153 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	plugin_types = (g_free (plugin_types), NULL);
#line 829 "synapse-main.c"
}


void synapse_ui_launcher_show_ui (SynapseUILauncher* self) {
	SynapseGuiIController* _tmp0_ = NULL;
	SynapseGuiIController* _tmp1_ = NULL;
#line 203 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_return_if_fail (self != NULL);
#line 205 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_ = self->priv->controller;
#line 205 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	if (_tmp0_ == NULL) {
#line 205 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		return;
#line 844 "synapse-main.c"
	}
#line 206 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp1_ = self->priv->controller;
#line 206 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_gui_icontroller_summon_or_vanish (_tmp1_);
#line 850 "synapse-main.c"
}


static void _synapse_ui_launcher_handle_shortcut_keybinder_handler (const gchar* keystring, void* udata) {
#line 214 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_ui_launcher_handle_shortcut (keystring, udata);
#line 857 "synapse-main.c"
}


static void synapse_ui_launcher_bind_keyboard_shortcut (SynapseUILauncher* self) {
	SynapseGuiKeyComboConfig* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	SynapseGuiSettingsWindow* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
#line 209 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_return_if_fail (self != NULL);
#line 211 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_ = self->priv->key_combo_config;
#line 211 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp1_ = synapse_gui_key_combo_config_get_activate (_tmp0_);
#line 211 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp2_ = _tmp1_;
#line 211 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 211 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_free0 (self->priv->current_shortcut);
#line 211 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	self->priv->current_shortcut = _tmp3_;
#line 212 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp4_ = self->priv->current_shortcut;
#line 212 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_message ("synapse-main.vala:212: Binding activation to %s", _tmp4_);
#line 213 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp5_ = self->priv->settings;
#line 213 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp6_ = self->priv->current_shortcut;
#line 213 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_gui_settings_window_set_keybinding (_tmp5_, _tmp6_, FALSE);
#line 214 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp7_ = self->priv->current_shortcut;
#line 214 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	keybinder_bind (_tmp7_, _synapse_ui_launcher_handle_shortcut_keybinder_handler, self);
#line 898 "synapse-main.c"
}


static void synapse_ui_launcher_handle_shortcut (const gchar* key, void* data) {
	void* _tmp0_ = NULL;
#line 217 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_return_if_fail (key != NULL);
#line 219 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_ = data;
#line 219 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_ui_launcher_show_ui (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, SYNAPSE_TYPE_UI_LAUNCHER, SynapseUILauncher));
#line 910 "synapse-main.c"
}


static void synapse_ui_launcher_change_keyboard_shortcut (SynapseUILauncher* self, const gchar* key) {
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
#line 222 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_return_if_fail (self != NULL);
#line 222 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_return_if_fail (key != NULL);
#line 224 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_ = self->priv->current_shortcut;
#line 224 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	keybinder_unbind (_tmp0_, _synapse_ui_launcher_handle_shortcut_keybinder_handler);
#line 225 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp1_ = key;
#line 225 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp2_ = g_strdup (_tmp1_);
#line 225 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_free0 (self->priv->current_shortcut);
#line 225 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	self->priv->current_shortcut = _tmp2_;
#line 226 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp3_ = self->priv->current_shortcut;
#line 226 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	keybinder_bind (_tmp3_, _synapse_ui_launcher_handle_shortcut_keybinder_handler, self);
#line 939 "synapse-main.c"
}


void synapse_ui_launcher_run (SynapseUILauncher* self) {
#line 229 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_return_if_fail (self != NULL);
#line 231 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_unsetenv ("DESKTOP_AUTOSTART_ID");
#line 232 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gdk_window_process_all_updates ();
#line 233 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	gtk_main ();
#line 952 "synapse-main.c"
}


static void synapse_ui_launcher_load_custom_style (void) {
	gchar* custom_gtkrc = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
#line 238 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_ = g_get_user_config_dir ();
#line 238 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp1_ = g_build_filename (_tmp0_, "synapse", "gtkrc", NULL);
#line 238 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	custom_gtkrc = _tmp1_;
#line 243 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp2_ = custom_gtkrc;
#line 243 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp3_ = g_file_test (_tmp2_, G_FILE_TEST_EXISTS);
#line 243 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	if (_tmp3_) {
#line 974 "synapse-main.c"
		const gchar* _tmp4_ = NULL;
#line 245 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_tmp4_ = custom_gtkrc;
#line 245 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		gtk_rc_add_default_file (_tmp4_);
#line 246 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		gtk_rc_reparse_all ();
#line 982 "synapse-main.c"
	}
#line 236 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_free0 (custom_gtkrc);
#line 986 "synapse-main.c"
}


static gboolean string_contains (const gchar* self, const gchar* needle) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 1278 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, FALSE);
#line 1278 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, FALSE);
#line 1279 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp0_ = needle;
#line 1279 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp1_ = strstr ((gchar*) self, (gchar*) _tmp0_);
#line 1279 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	result = _tmp1_ != NULL;
#line 1279 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	return result;
#line 1006 "synapse-main.c"
}


static void synapse_ui_launcher_ibus_fix (void) {
	gchar* ibus_no_snooper = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	const gchar* _tmp3_ = NULL;
	const gchar* _tmp5_ = NULL;
	gboolean _tmp6_ = FALSE;
	const gchar* _tmp7_ = NULL;
	gboolean _tmp8_ = FALSE;
	const gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
#line 253 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_ = g_getenv ("IBUS_NO_SNOOPER_APPS");
#line 253 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 253 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	ibus_no_snooper = _tmp1_;
#line 254 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp3_ = ibus_no_snooper;
#line 254 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	if (_tmp3_ == NULL) {
#line 254 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_tmp2_ = TRUE;
#line 1035 "synapse-main.c"
	} else {
		const gchar* _tmp4_ = NULL;
#line 254 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_tmp4_ = ibus_no_snooper;
#line 254 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_tmp2_ = g_strcmp0 (_tmp4_, "") == 0;
#line 1042 "synapse-main.c"
	}
#line 254 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	if (_tmp2_) {
#line 256 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		g_setenv ("IBUS_NO_SNOOPER_APPS", "synapse", TRUE);
#line 257 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_g_free0 (ibus_no_snooper);
#line 257 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		return;
#line 1052 "synapse-main.c"
	}
#line 259 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp5_ = ibus_no_snooper;
#line 259 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp6_ = string_contains (_tmp5_, "synapse");
#line 259 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	if (_tmp6_) {
#line 259 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_g_free0 (ibus_no_snooper);
#line 259 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		return;
#line 1064 "synapse-main.c"
	}
#line 261 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp7_ = ibus_no_snooper;
#line 261 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp8_ = g_str_has_suffix (_tmp7_, ",");
#line 261 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	if (!_tmp8_) {
#line 1072 "synapse-main.c"
		const gchar* _tmp9_ = NULL;
		gchar* _tmp10_ = NULL;
#line 262 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_tmp9_ = ibus_no_snooper;
#line 262 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_tmp10_ = g_strconcat (_tmp9_, ",", NULL);
#line 262 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_g_free0 (ibus_no_snooper);
#line 262 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		ibus_no_snooper = _tmp10_;
#line 1083 "synapse-main.c"
	}
#line 263 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp11_ = ibus_no_snooper;
#line 263 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp12_ = g_strconcat (_tmp11_, "synapse", NULL);
#line 263 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_free0 (ibus_no_snooper);
#line 263 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	ibus_no_snooper = _tmp12_;
#line 264 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp13_ = ibus_no_snooper;
#line 264 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_setenv ("IBUS_NO_SNOOPER_APPS", _tmp13_, TRUE);
#line 250 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_free0 (ibus_no_snooper);
#line 1099 "synapse-main.c"
}


static Block2Data* block2_data_ref (Block2Data* _data2_) {
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_atomic_int_inc (&_data2_->_ref_count_);
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	return _data2_;
#line 1108 "synapse-main.c"
}


static void block2_data_unref (void * _userdata_) {
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_g_object_unref0 (_data2_->launcher);
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		g_slice_free (Block2Data, _data2_);
#line 1121 "synapse-main.c"
	}
}


static void ____lambda45_ (Block2Data* _data2_) {
	SynapseUILauncher* _tmp0_ = NULL;
#line 299 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_ = _data2_->launcher;
#line 299 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_ui_launcher_show_ui (_tmp0_);
#line 1132 "synapse-main.c"
}


static void _____lambda45__g_application_activate (GApplication* _sender, gpointer self) {
#line 298 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	____lambda45_ (self);
#line 1139 "synapse-main.c"
}


gint synapse_ui_launcher_main (gchar** argv, int argv_length1) {
	gint result = 0;
	GOptionContext* context = NULL;
	GOptionContext* _tmp0_ = NULL;
	GOptionContext* _tmp1_ = NULL;
	GOptionContext* _tmp2_ = NULL;
	GOptionGroup* _tmp3_ = NULL;
	GError * _inner_error_ = NULL;
#line 269 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_utils_logger_initialize ();
#line 270 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_message ("synapse-main.vala:270: Starting up...");
#line 271 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_ui_launcher_ibus_fix ();
#line 273 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	setlocale (LC_ALL, "");
#line 274 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	bindtextdomain (GETTEXT_PACKAGE, DATADIR "/locale");
#line 275 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
#line 276 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	textdomain (GETTEXT_PACKAGE);
#line 278 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_ = g_option_context_new (" - Synapse");
#line 278 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	context = _tmp0_;
#line 279 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp1_ = context;
#line 279 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_option_context_add_main_entries (_tmp1_, SYNAPSE_UI_LAUNCHER_options, NULL);
#line 280 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp2_ = context;
#line 280 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp3_ = gtk_get_option_group (FALSE);
#line 280 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_option_context_add_group (_tmp2_, _tmp3_);
#line 1179 "synapse-main.c"
	{
		GOptionContext* _tmp4_ = NULL;
		GApplication* app = NULL;
		GApplication* _tmp5_ = NULL;
		gboolean _tmp6_ = FALSE;
		gboolean _tmp7_ = FALSE;
		GApplication* _tmp8_ = NULL;
		gboolean _tmp9_ = FALSE;
#line 283 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_tmp4_ = context;
#line 283 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		g_option_context_parse (_tmp4_, &argv_length1, &argv, &_inner_error_);
#line 283 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1194 "synapse-main.c"
			goto __catch0_g_error;
		}
#line 286 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		synapse_ui_launcher_load_custom_style ();
#line 287 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		gtk_init (&argv_length1, &argv);
#line 288 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		notify_init ("synapse");
#line 290 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_tmp5_ = g_application_new ("org.gnome.Synapse", G_APPLICATION_FLAGS_NONE);
#line 290 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		app = _tmp5_;
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_tmp8_ = app;
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_tmp9_ = g_application_register (_tmp8_, NULL, &_inner_error_);
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_tmp7_ = _tmp9_;
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			_g_object_unref0 (app);
#line 1217 "synapse-main.c"
			goto __catch0_g_error;
		}
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		if (!_tmp7_) {
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			_tmp6_ = TRUE;
#line 1224 "synapse-main.c"
		} else {
			GApplication* _tmp10_ = NULL;
			gboolean _tmp11_ = FALSE;
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			_tmp10_ = app;
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			_tmp11_ = g_application_get_is_remote (_tmp10_);
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			_tmp6_ = _tmp11_;
#line 1234 "synapse-main.c"
		}
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		if (_tmp6_) {
#line 1238 "synapse-main.c"
			GApplication* _tmp12_ = NULL;
#line 292 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			g_message ("synapse-main.vala:292: Synapse is already running, activating...");
#line 293 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			_tmp12_ = app;
#line 293 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			g_application_activate (_tmp12_);
#line 1246 "synapse-main.c"
		} else {
			Block2Data* _data2_;
			SynapseUILauncher* _tmp13_ = NULL;
			GApplication* _tmp14_ = NULL;
			SynapseUILauncher* _tmp15_ = NULL;
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			_data2_ = g_slice_new0 (Block2Data);
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			_data2_->_ref_count_ = 1;
#line 297 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			_tmp13_ = synapse_ui_launcher_new ();
#line 297 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			_data2_->launcher = _tmp13_;
#line 298 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			_tmp14_ = app;
#line 298 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			g_signal_connect_data (_tmp14_, "activate", (GCallback) _____lambda45__g_application_activate, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
#line 302 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			_tmp15_ = _data2_->launcher;
#line 302 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			synapse_ui_launcher_run (_tmp15_);
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			block2_data_unref (_data2_);
#line 291 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
			_data2_ = NULL;
#line 1272 "synapse-main.c"
		}
#line 281 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_g_object_unref0 (app);
#line 1276 "synapse-main.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* err = NULL;
		GError* _tmp16_ = NULL;
		const gchar* _tmp17_ = NULL;
#line 281 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		err = _inner_error_;
#line 281 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_inner_error_ = NULL;
#line 307 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_tmp16_ = err;
#line 307 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_tmp17_ = _tmp16_->message;
#line 307 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		g_warning ("synapse-main.vala:307: %s", _tmp17_);
#line 281 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_g_error_free0 (err);
#line 1296 "synapse-main.c"
	}
	__finally0:
#line 281 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 281 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		_g_option_context_free0 (context);
#line 281 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 281 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		g_clear_error (&_inner_error_);
#line 281 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
		return 0;
#line 1309 "synapse-main.c"
	}
#line 310 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	result = 0;
#line 310 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_option_context_free0 (context);
#line 310 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	return result;
#line 1317 "synapse-main.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,32,0)
	g_thread_init (NULL);
#endif
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 267 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	return synapse_ui_launcher_main (argv, argc);
#line 1330 "synapse-main.c"
}


static void synapse_ui_launcher_class_init (SynapseUILauncherClass * klass) {
#line 28 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_ui_launcher_parent_class = g_type_class_peek_parent (klass);
#line 28 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	g_type_class_add_private (klass, sizeof (SynapseUILauncherPrivate));
#line 28 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	G_OBJECT_CLASS (klass)->finalize = synapse_ui_launcher_finalize;
#line 1341 "synapse-main.c"
}


static void synapse_ui_launcher_instance_init (SynapseUILauncher * self) {
#line 28 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	self->priv = SYNAPSE_UI_LAUNCHER_GET_PRIVATE (self);
#line 1348 "synapse-main.c"
}


static void synapse_ui_launcher_finalize (GObject* obj) {
	SynapseUILauncher * self;
	SynapseConfigService* _tmp0_ = NULL;
#line 28 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYNAPSE_TYPE_UI_LAUNCHER, SynapseUILauncher);
#line 100 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_tmp0_ = self->priv->config;
#line 100 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	synapse_config_service_save (_tmp0_);
#line 42 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (self->priv->settings);
#line 43 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (self->priv->data_sink);
#line 44 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (self->priv->key_combo_config);
#line 45 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (self->priv->category_config);
#line 46 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_free0 (self->priv->current_shortcut);
#line 47 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (self->priv->config);
#line 51 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (self->priv->status_icon);
#line 53 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	_g_object_unref0 (self->priv->controller);
#line 55 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/synapse-main.vala"
	G_OBJECT_CLASS (synapse_ui_launcher_parent_class)->finalize (obj);
#line 1379 "synapse-main.c"
}


GType synapse_ui_launcher_get_type (void) {
	static volatile gsize synapse_ui_launcher_type_id__volatile = 0;
	if (g_once_init_enter (&synapse_ui_launcher_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SynapseUILauncherClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synapse_ui_launcher_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynapseUILauncher), 0, (GInstanceInitFunc) synapse_ui_launcher_instance_init, NULL };
		GType synapse_ui_launcher_type_id;
		synapse_ui_launcher_type_id = g_type_register_static (G_TYPE_OBJECT, "SynapseUILauncher", &g_define_type_info, 0);
		g_once_init_leave (&synapse_ui_launcher_type_id__volatile, synapse_ui_launcher_type_id);
	}
	return synapse_ui_launcher_type_id__volatile;
}



