/* tile-view.c generated by valac 0.28.1, the Vala compiler
 * generated from tile-view.vala, do not modify */

/*
 * Copyright (C) 2010 Michal Hruby <michal.mhr@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA.
 *
 * Authored by Michal Hruby <michal.mhr@gmail.com>
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <cairo.h>
#include <float.h>
#include <math.h>


#define UI_WIDGETS_TYPE_TILE_VIEW (ui_widgets_tile_view_get_type ())
#define UI_WIDGETS_TILE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UI_WIDGETS_TYPE_TILE_VIEW, UIWidgetsTileView))
#define UI_WIDGETS_TILE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UI_WIDGETS_TYPE_TILE_VIEW, UIWidgetsTileViewClass))
#define UI_WIDGETS_IS_TILE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UI_WIDGETS_TYPE_TILE_VIEW))
#define UI_WIDGETS_IS_TILE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UI_WIDGETS_TYPE_TILE_VIEW))
#define UI_WIDGETS_TILE_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UI_WIDGETS_TYPE_TILE_VIEW, UIWidgetsTileViewClass))

typedef struct _UIWidgetsTileView UIWidgetsTileView;
typedef struct _UIWidgetsTileViewClass UIWidgetsTileViewClass;
typedef struct _UIWidgetsTileViewPrivate UIWidgetsTileViewPrivate;

#define UI_WIDGETS_TYPE_ABSTRACT_TILE_OBJECT (ui_widgets_abstract_tile_object_get_type ())
#define UI_WIDGETS_ABSTRACT_TILE_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UI_WIDGETS_TYPE_ABSTRACT_TILE_OBJECT, UIWidgetsAbstractTileObject))
#define UI_WIDGETS_ABSTRACT_TILE_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UI_WIDGETS_TYPE_ABSTRACT_TILE_OBJECT, UIWidgetsAbstractTileObjectClass))
#define UI_WIDGETS_IS_ABSTRACT_TILE_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UI_WIDGETS_TYPE_ABSTRACT_TILE_OBJECT))
#define UI_WIDGETS_IS_ABSTRACT_TILE_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UI_WIDGETS_TYPE_ABSTRACT_TILE_OBJECT))
#define UI_WIDGETS_ABSTRACT_TILE_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UI_WIDGETS_TYPE_ABSTRACT_TILE_OBJECT, UIWidgetsAbstractTileObjectClass))

typedef struct _UIWidgetsAbstractTileObject UIWidgetsAbstractTileObject;
typedef struct _UIWidgetsAbstractTileObjectClass UIWidgetsAbstractTileObjectClass;

#define UI_WIDGETS_TYPE_TILE (ui_widgets_tile_get_type ())
#define UI_WIDGETS_TILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UI_WIDGETS_TYPE_TILE, UIWidgetsTile))
#define UI_WIDGETS_TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UI_WIDGETS_TYPE_TILE, UIWidgetsTileClass))
#define UI_WIDGETS_IS_TILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UI_WIDGETS_TYPE_TILE))
#define UI_WIDGETS_IS_TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UI_WIDGETS_TYPE_TILE))
#define UI_WIDGETS_TILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UI_WIDGETS_TYPE_TILE, UIWidgetsTileClass))

typedef struct _UIWidgetsTile UIWidgetsTile;
typedef struct _UIWidgetsTileClass UIWidgetsTileClass;
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
#define _cairo_region_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_region_destroy (var), NULL)))

struct _UIWidgetsTileView {
	GtkEventBox parent_instance;
	UIWidgetsTileViewPrivate * priv;
	gint selected_index;
};

struct _UIWidgetsTileViewClass {
	GtkEventBoxClass parent_class;
	void (*append_tile) (UIWidgetsTileView* self, UIWidgetsAbstractTileObject* tile_obj);
	void (*remove_tile) (UIWidgetsTileView* self, UIWidgetsAbstractTileObject* tile_obj);
	void (*clear_selection) (UIWidgetsTileView* self);
	UIWidgetsAbstractTileObject* (*get_current_tile) (UIWidgetsTileView* self);
	void (*on_tile_active_changed) (UIWidgetsTileView* self, UIWidgetsTile* tile);
	void (*on_tile_size_allocated) (UIWidgetsTileView* self, GtkWidget* w, GtkAllocation* alloc);
};

struct _UIWidgetsTileViewPrivate {
	GList* tiles;
	GtkBox* box;
	gint _icon_size;
	gboolean changing_style;
};


static gpointer ui_widgets_tile_view_parent_class = NULL;

GType ui_widgets_tile_view_get_type (void) G_GNUC_CONST;
GType ui_widgets_abstract_tile_object_get_type (void) G_GNUC_CONST;
GType ui_widgets_tile_get_type (void) G_GNUC_CONST;
#define UI_WIDGETS_TILE_VIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), UI_WIDGETS_TYPE_TILE_VIEW, UIWidgetsTileViewPrivate))
enum  {
	UI_WIDGETS_TILE_VIEW_DUMMY_PROPERTY,
	UI_WIDGETS_TILE_VIEW_ICON_SIZE
};
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
UIWidgetsTileView* ui_widgets_tile_view_new (void);
UIWidgetsTileView* ui_widgets_tile_view_construct (GType object_type);
gboolean ui_widgets_tile_view_on_button_press (UIWidgetsTileView* self, GdkEventButton* event);
static gboolean _ui_widgets_tile_view_on_button_press_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
gboolean ui_widgets_tile_view_on_key_press (UIWidgetsTileView* self, GdkEventKey* event);
static gboolean _ui_widgets_tile_view_on_key_press_gtk_widget_key_press_event (GtkWidget* _sender, GdkEventKey* event, gpointer self);
void ui_widgets_tile_view_append_tile (UIWidgetsTileView* self, UIWidgetsAbstractTileObject* tile_obj);
static void ui_widgets_tile_view_real_append_tile (UIWidgetsTileView* self, UIWidgetsAbstractTileObject* tile_obj);
gint ui_widgets_tile_view_get_icon_size (UIWidgetsTileView* self);
UIWidgetsTile* ui_widgets_tile_new (UIWidgetsAbstractTileObject* obj, gint icon_size);
UIWidgetsTile* ui_widgets_tile_construct (GType object_type, UIWidgetsAbstractTileObject* obj, gint icon_size);
void ui_widgets_tile_set_owner (UIWidgetsTile* self, UIWidgetsTileView* value);
void ui_widgets_tile_view_on_tile_active_changed (UIWidgetsTileView* self, UIWidgetsTile* tile);
static void _ui_widgets_tile_view_on_tile_active_changed_ui_widgets_tile_active_changed (UIWidgetsTile* _sender, gpointer self);
void ui_widgets_tile_view_on_tile_size_allocated (UIWidgetsTileView* self, GtkWidget* w, GtkAllocation* alloc);
static void _ui_widgets_tile_view_on_tile_size_allocated_gtk_widget_size_allocate (GtkWidget* _sender, GtkAllocation* allocation, gpointer self);
void ui_widgets_tile_view_remove_tile (UIWidgetsTileView* self, UIWidgetsAbstractTileObject* tile_obj);
static void ui_widgets_tile_view_real_remove_tile (UIWidgetsTileView* self, UIWidgetsAbstractTileObject* tile_obj);
UIWidgetsAbstractTileObject* ui_widgets_tile_get_owned_object (UIWidgetsTile* self);
void ui_widgets_tile_view_clear_selection (UIWidgetsTileView* self);
GList* ui_widgets_tile_view_get_tiles (UIWidgetsTileView* self);
void ui_widgets_tile_view_clear (UIWidgetsTileView* self);
static void ui_widgets_tile_view_real_clear_selection (UIWidgetsTileView* self);
void ui_widgets_tile_set_selected (UIWidgetsTile* self, gboolean selected);
UIWidgetsAbstractTileObject* ui_widgets_tile_view_get_current_tile (UIWidgetsTileView* self);
static UIWidgetsAbstractTileObject* ui_widgets_tile_view_real_get_current_tile (UIWidgetsTileView* self);
static void ui_widgets_tile_view_real_style_updated (GtkWidget* base);
static void ui_widgets_tile_view_real_on_tile_active_changed (UIWidgetsTileView* self, UIWidgetsTile* tile);
void ui_widgets_tile_update_state (UIWidgetsTile* self);
static void ui_widgets_tile_view_real_on_tile_size_allocated (UIWidgetsTileView* self, GtkWidget* w, GtkAllocation* alloc);
void ui_widgets_tile_view_select (UIWidgetsTileView* self, gint index);
void ui_widgets_tile_view_set_icon_size (UIWidgetsTileView* self, gint value);
static void ui_widgets_tile_view_finalize (GObject* obj);
static void _vala_ui_widgets_tile_view_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_ui_widgets_tile_view_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static void _g_object_unref0_ (gpointer var) {
#line 28 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 146 "tile-view.c"
}


static void _g_list_free__g_object_unref0_ (GList* self) {
#line 28 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
#line 28 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_list_free (self);
#line 155 "tile-view.c"
}


static gboolean _ui_widgets_tile_view_on_button_press_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = ui_widgets_tile_view_on_button_press ((UIWidgetsTileView*) self, event);
#line 39 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	return result;
#line 164 "tile-view.c"
}


static gboolean _ui_widgets_tile_view_on_key_press_gtk_widget_key_press_event (GtkWidget* _sender, GdkEventKey* event, gpointer self) {
	gboolean result;
	result = ui_widgets_tile_view_on_key_press ((UIWidgetsTileView*) self, event);
#line 40 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	return result;
#line 173 "tile-view.c"
}


UIWidgetsTileView* ui_widgets_tile_view_construct (GType object_type) {
	UIWidgetsTileView * self = NULL;
	GtkBox* _tmp0_ = NULL;
	GtkBox* _tmp1_ = NULL;
	GtkBox* _tmp2_ = NULL;
#line 37 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	self = (UIWidgetsTileView*) g_object_new (object_type, "can-focus", TRUE, "visible-window", FALSE, NULL);
#line 39 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_signal_connect_object ((GtkWidget*) self, "button-press-event", (GCallback) _ui_widgets_tile_view_on_button_press_gtk_widget_button_press_event, self, 0);
#line 40 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_signal_connect_object ((GtkWidget*) self, "key-press-event", (GCallback) _ui_widgets_tile_view_on_key_press_gtk_widget_key_press_event, self, 0);
#line 41 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp0_ = self->priv->box;
#line 41 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	gtk_box_set_homogeneous (_tmp0_, FALSE);
#line 42 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp1_ = self->priv->box;
#line 42 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	gtk_widget_show ((GtkWidget*) _tmp1_);
#line 43 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp2_ = self->priv->box;
#line 43 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp2_);
#line 45 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_signal_emit_by_name ((GtkWidget*) self, "style-updated");
#line 35 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	return self;
#line 204 "tile-view.c"
}


UIWidgetsTileView* ui_widgets_tile_view_new (void) {
#line 35 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	return ui_widgets_tile_view_construct (UI_WIDGETS_TYPE_TILE_VIEW);
#line 211 "tile-view.c"
}


static void _ui_widgets_tile_view_on_tile_active_changed_ui_widgets_tile_active_changed (UIWidgetsTile* _sender, gpointer self) {
#line 52 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	ui_widgets_tile_view_on_tile_active_changed ((UIWidgetsTileView*) self, _sender);
#line 218 "tile-view.c"
}


static void _ui_widgets_tile_view_on_tile_size_allocated_gtk_widget_size_allocate (GtkWidget* _sender, GtkAllocation* allocation, gpointer self) {
#line 53 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	ui_widgets_tile_view_on_tile_size_allocated ((UIWidgetsTileView*) self, _sender, allocation);
#line 225 "tile-view.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 56 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	return self ? g_object_ref (self) : NULL;
#line 232 "tile-view.c"
}


static void ui_widgets_tile_view_real_append_tile (UIWidgetsTileView* self, UIWidgetsAbstractTileObject* tile_obj) {
	UIWidgetsTile* tile = NULL;
	UIWidgetsAbstractTileObject* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	UIWidgetsTile* _tmp2_ = NULL;
	UIWidgetsTile* _tmp3_ = NULL;
	GtkBox* _tmp4_ = NULL;
#line 48 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_if_fail (tile_obj != NULL);
#line 50 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp0_ = tile_obj;
#line 50 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp1_ = self->priv->_icon_size;
#line 50 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp2_ = ui_widgets_tile_new (_tmp0_, _tmp1_);
#line 50 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_object_ref_sink (_tmp2_);
#line 50 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	tile = _tmp2_;
#line 51 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	ui_widgets_tile_set_owner (tile, self);
#line 52 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_signal_connect_object (tile, "active-changed", (GCallback) _ui_widgets_tile_view_on_tile_active_changed_ui_widgets_tile_active_changed, self, 0);
#line 53 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_signal_connect_object ((GtkWidget*) tile, "size-allocate", (GCallback) _ui_widgets_tile_view_on_tile_size_allocated_gtk_widget_size_allocate, self, 0);
#line 54 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	gtk_widget_show ((GtkWidget*) tile);
#line 56 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp3_ = _g_object_ref0 (tile);
#line 56 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	self->priv->tiles = g_list_append (self->priv->tiles, _tmp3_);
#line 58 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp4_ = self->priv->box;
#line 58 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	gtk_box_pack_start (_tmp4_, (GtkWidget*) tile, FALSE, FALSE, (guint) 0);
#line 48 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_g_object_unref0 (tile);
#line 273 "tile-view.c"
}


void ui_widgets_tile_view_append_tile (UIWidgetsTileView* self, UIWidgetsAbstractTileObject* tile_obj) {
#line 48 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_if_fail (self != NULL);
#line 48 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	UI_WIDGETS_TILE_VIEW_GET_CLASS (self)->append_tile (self, tile_obj);
#line 282 "tile-view.c"
}


static void ui_widgets_tile_view_real_remove_tile (UIWidgetsTileView* self, UIWidgetsAbstractTileObject* tile_obj) {
	UIWidgetsTile* tile = NULL;
	GList* _tmp0_ = NULL;
	UIWidgetsTile* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	GList* _tmp8_ = NULL;
	UIWidgetsTile* _tmp9_ = NULL;
	gint _tmp10_ = 0;
	UIWidgetsTile* _tmp11_ = NULL;
	UIWidgetsTile* _tmp12_ = NULL;
	guint _tmp13_ = 0U;
	UIWidgetsTile* _tmp14_ = NULL;
	guint _tmp15_ = 0U;
	UIWidgetsTile* _tmp16_ = NULL;
	GtkBox* _tmp17_ = NULL;
	UIWidgetsTile* _tmp18_ = NULL;
	UIWidgetsTile* _tmp19_ = NULL;
#line 61 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_if_fail (tile_obj != NULL);
#line 63 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	tile = NULL;
#line 64 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp0_ = self->priv->tiles;
#line 309 "tile-view.c"
	{
		GList* t_collection = NULL;
		GList* t_it = NULL;
#line 64 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		t_collection = _tmp0_;
#line 64 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		for (t_it = t_collection; t_it != NULL; t_it = t_it->next) {
#line 317 "tile-view.c"
			UIWidgetsTile* t = NULL;
#line 64 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			t = (UIWidgetsTile*) t_it->data;
#line 321 "tile-view.c"
			{
				UIWidgetsTile* _tmp1_ = NULL;
				UIWidgetsAbstractTileObject* _tmp2_ = NULL;
				UIWidgetsAbstractTileObject* _tmp3_ = NULL;
				UIWidgetsAbstractTileObject* _tmp4_ = NULL;
#line 66 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp1_ = t;
#line 66 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp2_ = ui_widgets_tile_get_owned_object (_tmp1_);
#line 66 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp3_ = _tmp2_;
#line 66 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp4_ = tile_obj;
#line 66 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				if (_tmp3_ == _tmp4_) {
#line 337 "tile-view.c"
					UIWidgetsTile* _tmp5_ = NULL;
#line 68 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
					_tmp5_ = t;
#line 68 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
					tile = _tmp5_;
#line 69 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
					break;
#line 345 "tile-view.c"
				}
			}
		}
	}
#line 73 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp6_ = tile;
#line 73 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	if (_tmp6_ == NULL) {
#line 75 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		g_warning ("tile-view.vala:75: Container does not own this AbstractTileObject!");
#line 76 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		return;
#line 358 "tile-view.c"
	}
#line 79 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp7_ = self->selected_index;
#line 79 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp8_ = self->priv->tiles;
#line 79 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp9_ = tile;
#line 79 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp10_ = g_list_index (_tmp8_, _tmp9_);
#line 79 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	if (_tmp7_ == _tmp10_) {
#line 81 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		ui_widgets_tile_view_clear_selection (self);
#line 372 "tile-view.c"
	}
#line 84 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp11_ = tile;
#line 84 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	gtk_widget_hide ((GtkWidget*) _tmp11_);
#line 85 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp12_ = tile;
#line 85 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_signal_parse_name ("active-changed", UI_WIDGETS_TYPE_TILE, &_tmp13_, NULL, FALSE);
#line 85 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_signal_handlers_disconnect_matched (_tmp12_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp13_, 0, NULL, (GCallback) _ui_widgets_tile_view_on_tile_active_changed_ui_widgets_tile_active_changed, self);
#line 86 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp14_ = tile;
#line 86 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_signal_parse_name ("size-allocate", gtk_widget_get_type (), &_tmp15_, NULL, FALSE);
#line 86 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_signal_handlers_disconnect_matched ((GtkWidget*) _tmp14_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp15_, 0, NULL, (GCallback) _ui_widgets_tile_view_on_tile_size_allocated_gtk_widget_size_allocate, self);
#line 87 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp16_ = tile;
#line 87 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	ui_widgets_tile_set_owner (_tmp16_, NULL);
#line 89 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp17_ = self->priv->box;
#line 89 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp18_ = tile;
#line 89 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	gtk_container_remove ((GtkContainer*) _tmp17_, (GtkWidget*) _tmp18_);
#line 90 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp19_ = tile;
#line 90 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	self->priv->tiles = g_list_remove (self->priv->tiles, _tmp19_);
#line 404 "tile-view.c"
}


void ui_widgets_tile_view_remove_tile (UIWidgetsTileView* self, UIWidgetsAbstractTileObject* tile_obj) {
#line 61 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_if_fail (self != NULL);
#line 61 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	UI_WIDGETS_TILE_VIEW_GET_CLASS (self)->remove_tile (self, tile_obj);
#line 413 "tile-view.c"
}


GList* ui_widgets_tile_view_get_tiles (UIWidgetsTileView* self) {
	GList* result = NULL;
	GList* _result_ = NULL;
	GList* _tmp0_ = NULL;
#line 93 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 95 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_result_ = NULL;
#line 97 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp0_ = self->priv->tiles;
#line 427 "tile-view.c"
	{
		GList* t_collection = NULL;
		GList* t_it = NULL;
#line 97 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		t_collection = _tmp0_;
#line 97 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		for (t_it = t_collection; t_it != NULL; t_it = t_it->next) {
#line 435 "tile-view.c"
			UIWidgetsTile* t = NULL;
#line 97 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			t = (UIWidgetsTile*) t_it->data;
#line 439 "tile-view.c"
			{
				UIWidgetsTile* _tmp1_ = NULL;
				UIWidgetsAbstractTileObject* _tmp2_ = NULL;
				UIWidgetsAbstractTileObject* _tmp3_ = NULL;
#line 99 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp1_ = t;
#line 99 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp2_ = ui_widgets_tile_get_owned_object (_tmp1_);
#line 99 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp3_ = _tmp2_;
#line 99 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_result_ = g_list_prepend (_result_, _tmp3_);
#line 452 "tile-view.c"
			}
		}
	}
#line 101 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_result_ = g_list_reverse (_result_);
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	result = _result_;
#line 103 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	return result;
#line 462 "tile-view.c"
}


void ui_widgets_tile_view_clear (UIWidgetsTileView* self) {
	GList* tiles_copy = NULL;
	GList* _tmp0_ = NULL;
	GList* _tmp1_ = NULL;
#line 106 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_if_fail (self != NULL);
#line 108 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp0_ = ui_widgets_tile_view_get_tiles (self);
#line 108 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	tiles_copy = _tmp0_;
#line 109 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp1_ = tiles_copy;
#line 478 "tile-view.c"
	{
		GList* to_collection = NULL;
		GList* to_it = NULL;
#line 109 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		to_collection = _tmp1_;
#line 109 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		for (to_it = to_collection; to_it != NULL; to_it = to_it->next) {
#line 486 "tile-view.c"
			UIWidgetsAbstractTileObject* to = NULL;
#line 109 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			to = (UIWidgetsAbstractTileObject*) to_it->data;
#line 490 "tile-view.c"
			{
				UIWidgetsAbstractTileObject* _tmp2_ = NULL;
#line 111 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp2_ = to;
#line 111 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				ui_widgets_tile_view_remove_tile (self, _tmp2_);
#line 497 "tile-view.c"
			}
		}
	}
#line 106 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_g_list_free0 (tiles_copy);
#line 503 "tile-view.c"
}


static void ui_widgets_tile_view_real_clear_selection (UIWidgetsTileView* self) {
	gint _tmp0_ = 0;
	GList* _tmp1_ = NULL;
	guint _tmp2_ = 0U;
	gint _tmp3_ = 0;
#line 117 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp0_ = self->selected_index;
#line 117 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp1_ = self->priv->tiles;
#line 117 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp2_ = g_list_length (_tmp1_);
#line 117 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp3_ = _tmp0_;
#line 117 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	if ((0 <= _tmp3_) && (_tmp3_ < _tmp2_)) {
#line 522 "tile-view.c"
		GList* _tmp4_ = NULL;
		gint _tmp5_ = 0;
		gconstpointer _tmp6_ = NULL;
#line 119 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp4_ = self->priv->tiles;
#line 119 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp5_ = self->selected_index;
#line 119 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp6_ = g_list_nth_data (_tmp4_, (guint) _tmp5_);
#line 119 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		ui_widgets_tile_set_selected ((UIWidgetsTile*) _tmp6_, FALSE);
#line 534 "tile-view.c"
	}
#line 122 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	self->selected_index = -1;
#line 538 "tile-view.c"
}


void ui_widgets_tile_view_clear_selection (UIWidgetsTileView* self) {
#line 115 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_if_fail (self != NULL);
#line 115 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	UI_WIDGETS_TILE_VIEW_GET_CLASS (self)->clear_selection (self);
#line 547 "tile-view.c"
}


static UIWidgetsAbstractTileObject* ui_widgets_tile_view_real_get_current_tile (UIWidgetsTileView* self) {
	UIWidgetsAbstractTileObject* result = NULL;
	gint _tmp0_ = 0;
	GList* _tmp1_ = NULL;
	guint _tmp2_ = 0U;
	gint _tmp3_ = 0;
#line 127 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp0_ = self->selected_index;
#line 127 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp1_ = self->priv->tiles;
#line 127 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp2_ = g_list_length (_tmp1_);
#line 127 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp3_ = _tmp0_;
#line 127 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	if ((0 <= _tmp3_) && (_tmp3_ < _tmp2_)) {
#line 567 "tile-view.c"
		GList* _tmp4_ = NULL;
		gint _tmp5_ = 0;
		gconstpointer _tmp6_ = NULL;
		UIWidgetsAbstractTileObject* _tmp7_ = NULL;
		UIWidgetsAbstractTileObject* _tmp8_ = NULL;
		UIWidgetsAbstractTileObject* _tmp9_ = NULL;
#line 129 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp4_ = self->priv->tiles;
#line 129 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp5_ = self->selected_index;
#line 129 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp6_ = g_list_nth_data (_tmp4_, (guint) _tmp5_);
#line 129 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp7_ = ui_widgets_tile_get_owned_object ((UIWidgetsTile*) _tmp6_);
#line 129 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp8_ = _tmp7_;
#line 129 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp9_ = _g_object_ref0 (_tmp8_);
#line 129 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		result = _tmp9_;
#line 129 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		return result;
#line 590 "tile-view.c"
	}
#line 132 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	result = NULL;
#line 132 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	return result;
#line 596 "tile-view.c"
}


UIWidgetsAbstractTileObject* ui_widgets_tile_view_get_current_tile (UIWidgetsTileView* self) {
#line 125 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 125 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	return UI_WIDGETS_TILE_VIEW_GET_CLASS (self)->get_current_tile (self);
#line 605 "tile-view.c"
}


static void ui_widgets_tile_view_real_style_updated (GtkWidget* base) {
	UIWidgetsTileView * self;
#line 137 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	self = (UIWidgetsTileView*) base;
#line 613 "tile-view.c"
}


static void ui_widgets_tile_view_real_on_tile_active_changed (UIWidgetsTileView* self, UIWidgetsTile* tile) {
	UIWidgetsTile* _tmp0_ = NULL;
	UIWidgetsAbstractTileObject* _tmp1_ = NULL;
	UIWidgetsAbstractTileObject* _tmp2_ = NULL;
	GList* _tmp3_ = NULL;
#line 148 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_if_fail (tile != NULL);
#line 150 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp0_ = tile;
#line 150 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp1_ = ui_widgets_tile_get_owned_object (_tmp0_);
#line 150 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp2_ = _tmp1_;
#line 150 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_signal_emit_by_name (_tmp2_, "active-changed");
#line 152 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp3_ = self->priv->tiles;
#line 634 "tile-view.c"
	{
		GList* t_collection = NULL;
		GList* t_it = NULL;
#line 152 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		t_collection = _tmp3_;
#line 152 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		for (t_it = t_collection; t_it != NULL; t_it = t_it->next) {
#line 642 "tile-view.c"
			UIWidgetsTile* t = NULL;
#line 152 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			t = (UIWidgetsTile*) t_it->data;
#line 646 "tile-view.c"
			{
				UIWidgetsTile* _tmp4_ = NULL;
#line 154 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp4_ = t;
#line 154 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				ui_widgets_tile_update_state (_tmp4_);
#line 653 "tile-view.c"
			}
		}
	}
}


void ui_widgets_tile_view_on_tile_active_changed (UIWidgetsTileView* self, UIWidgetsTile* tile) {
#line 148 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_if_fail (self != NULL);
#line 148 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	UI_WIDGETS_TILE_VIEW_GET_CLASS (self)->on_tile_active_changed (self, tile);
#line 665 "tile-view.c"
}


static void ui_widgets_tile_view_real_on_tile_size_allocated (UIWidgetsTileView* self, GtkWidget* w, GtkAllocation* alloc) {
	UIWidgetsTile* tile = NULL;
	GtkWidget* _tmp0_ = NULL;
	UIWidgetsTile* _tmp1_ = NULL;
	GtkScrolledWindow* scroll = NULL;
	GtkScrolledWindow* _tmp2_ = NULL;
	GtkContainer* _tmp3_ = NULL;
	GtkScrolledWindow* _tmp6_ = NULL;
	GtkScrolledWindow* _tmp7_ = NULL;
	GList* _tmp8_ = NULL;
	UIWidgetsTile* _tmp9_ = NULL;
	gint _tmp10_ = 0;
	gint _tmp11_ = 0;
	GtkAdjustment* scroll_vadj = NULL;
	GtkScrolledWindow* _tmp12_ = NULL;
	GtkAdjustment* _tmp13_ = NULL;
	GdkRectangle va = {0};
	GtkAdjustment* _tmp14_ = NULL;
	gdouble _tmp15_ = 0.0;
	GtkAllocation _tmp16_ = {0};
	gint _tmp17_ = 0;
	GtkContainer* _tmp18_ = NULL;
	gint _tmp19_ = 0;
	GdkRectangle _tmp20_ = {0};
	cairo_region_t* va_region = NULL;
	GdkRectangle _tmp21_ = {0};
	cairo_region_t* _tmp22_ = NULL;
	cairo_region_t* _tmp23_ = NULL;
	GtkAllocation _tmp24_ = {0};
	cairo_rectangle_int_t _tmp25_ = {0};
	cairo_region_overlap_t _tmp26_ = 0;
#line 158 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_if_fail (w != NULL);
#line 158 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_if_fail (alloc != NULL);
#line 160 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp0_ = w;
#line 160 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp1_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, UI_WIDGETS_TYPE_TILE) ? ((UIWidgetsTile*) _tmp0_) : NULL);
#line 160 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	tile = _tmp1_;
#line 161 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	scroll = NULL;
#line 163 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp3_ = (GtkContainer*) gtk_widget_get_parent ((GtkWidget*) self);
#line 163 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	if (_tmp3_ == NULL) {
#line 164 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp2_ = NULL;
#line 718 "tile-view.c"
	} else {
		GtkContainer* _tmp4_ = NULL;
		GtkContainer* _tmp5_ = NULL;
#line 164 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp4_ = (GtkContainer*) gtk_widget_get_parent ((GtkWidget*) self);
#line 164 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp5_ = (GtkContainer*) gtk_widget_get_parent ((GtkWidget*) _tmp4_);
#line 164 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp2_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp5_, gtk_scrolled_window_get_type ()) ? ((GtkScrolledWindow*) _tmp5_) : NULL;
#line 728 "tile-view.c"
	}
#line 163 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp6_ = _g_object_ref0 (_tmp2_);
#line 163 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_g_object_unref0 (scroll);
#line 163 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	scroll = _tmp6_;
#line 165 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp7_ = scroll;
#line 165 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	if (_tmp7_ == NULL) {
#line 167 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_g_object_unref0 (scroll);
#line 167 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_g_object_unref0 (tile);
#line 167 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		return;
#line 746 "tile-view.c"
	}
#line 170 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp8_ = self->priv->tiles;
#line 170 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp9_ = tile;
#line 170 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp10_ = g_list_index (_tmp8_, _tmp9_);
#line 170 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp11_ = self->selected_index;
#line 170 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	if (_tmp10_ != _tmp11_) {
#line 172 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_g_object_unref0 (scroll);
#line 172 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_g_object_unref0 (tile);
#line 172 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		return;
#line 764 "tile-view.c"
	}
#line 175 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp12_ = scroll;
#line 175 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp13_ = gtk_scrolled_window_get_vadjustment (_tmp12_);
#line 175 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	scroll_vadj = _tmp13_;
#line 176 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp14_ = scroll_vadj;
#line 176 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp15_ = gtk_adjustment_get_value (_tmp14_);
#line 176 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp16_ = *alloc;
#line 176 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp17_ = _tmp16_.width;
#line 176 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp18_ = (GtkContainer*) gtk_widget_get_parent ((GtkWidget*) self);
#line 176 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp19_ = gtk_widget_get_allocated_height ((GtkWidget*) _tmp18_);
#line 176 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp20_.x = 0;
#line 176 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp20_.y = (gint) _tmp15_;
#line 176 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp20_.width = _tmp17_;
#line 176 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp20_.height = _tmp19_;
#line 176 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	va = _tmp20_;
#line 179 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp21_ = va;
#line 179 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp22_ = cairo_region_create_rectangle (&_tmp21_);
#line 179 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	va_region = _tmp22_;
#line 180 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp23_ = va_region;
#line 180 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp24_ = *alloc;
#line 180 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp25_ = (cairo_rectangle_int_t) _tmp24_;
#line 180 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp26_ = cairo_region_contains_rectangle (_tmp23_, &_tmp25_);
#line 180 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	if (_tmp26_ != CAIRO_REGION_OVERLAP_IN) {
#line 810 "tile-view.c"
		gdouble delta = 0.0;
		GtkAllocation _tmp27_ = {0};
		gint _tmp28_ = 0;
		GtkAllocation _tmp29_ = {0};
		gint _tmp30_ = 0;
		GdkRectangle _tmp31_ = {0};
		gint _tmp32_ = 0;
		GdkRectangle _tmp33_ = {0};
		gint _tmp34_ = 0;
		GtkAdjustment* _tmp55_ = NULL;
		GdkRectangle _tmp56_ = {0};
		gint _tmp57_ = 0;
		gdouble _tmp58_ = 0.0;
#line 182 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		delta = 0.0;
#line 183 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp27_ = *alloc;
#line 183 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp28_ = _tmp27_.y;
#line 183 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp29_ = *alloc;
#line 183 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp30_ = _tmp29_.height;
#line 183 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp31_ = va;
#line 183 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp32_ = _tmp31_.y;
#line 183 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp33_ = va;
#line 183 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp34_ = _tmp33_.height;
#line 183 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		if ((_tmp28_ + _tmp30_) > (_tmp32_ + _tmp34_)) {
#line 844 "tile-view.c"
			GtkAllocation _tmp35_ = {0};
			gint _tmp36_ = 0;
			GtkAllocation _tmp37_ = {0};
			gint _tmp38_ = 0;
			GdkRectangle _tmp39_ = {0};
			gint _tmp40_ = 0;
			GdkRectangle _tmp41_ = {0};
			gint _tmp42_ = 0;
			gdouble _tmp43_ = 0.0;
			GtkStyle* _tmp44_ = NULL;
			GtkStyle* _tmp45_ = NULL;
			gint _tmp46_ = 0;
#line 185 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp35_ = *alloc;
#line 185 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp36_ = _tmp35_.y;
#line 185 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp37_ = *alloc;
#line 185 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp38_ = _tmp37_.height;
#line 185 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp39_ = va;
#line 185 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp40_ = _tmp39_.y;
#line 185 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp41_ = va;
#line 185 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp42_ = _tmp41_.height;
#line 185 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			delta = (gdouble) ((_tmp36_ + _tmp38_) - (_tmp40_ + _tmp42_));
#line 186 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp43_ = delta;
#line 186 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp44_ = gtk_widget_get_style ((GtkWidget*) self);
#line 186 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp45_ = _tmp44_;
#line 186 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp46_ = _tmp45_->ythickness;
#line 186 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			delta = _tmp43_ + (_tmp46_ * 2);
#line 885 "tile-view.c"
		} else {
			GtkAllocation _tmp47_ = {0};
			gint _tmp48_ = 0;
			GdkRectangle _tmp49_ = {0};
			gint _tmp50_ = 0;
#line 188 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp47_ = *alloc;
#line 188 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp48_ = _tmp47_.y;
#line 188 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp49_ = va;
#line 188 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp50_ = _tmp49_.y;
#line 188 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			if (_tmp48_ < _tmp50_) {
#line 901 "tile-view.c"
				GtkAllocation _tmp51_ = {0};
				gint _tmp52_ = 0;
				GdkRectangle _tmp53_ = {0};
				gint _tmp54_ = 0;
#line 190 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp51_ = *alloc;
#line 190 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp52_ = _tmp51_.y;
#line 190 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp53_ = va;
#line 190 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp54_ = _tmp53_.y;
#line 190 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				delta = (gdouble) (_tmp52_ - _tmp54_);
#line 916 "tile-view.c"
			}
		}
#line 193 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp55_ = scroll_vadj;
#line 193 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp56_ = va;
#line 193 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp57_ = _tmp56_.y;
#line 193 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp58_ = delta;
#line 193 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		gtk_adjustment_set_value (_tmp55_, _tmp57_ + _tmp58_);
#line 194 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		gtk_widget_queue_draw ((GtkWidget*) self);
#line 931 "tile-view.c"
	}
#line 158 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_cairo_region_destroy0 (va_region);
#line 158 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_g_object_unref0 (scroll);
#line 158 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_g_object_unref0 (tile);
#line 939 "tile-view.c"
}


void ui_widgets_tile_view_on_tile_size_allocated (UIWidgetsTileView* self, GtkWidget* w, GtkAllocation* alloc) {
#line 158 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_if_fail (self != NULL);
#line 158 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	UI_WIDGETS_TILE_VIEW_GET_CLASS (self)->on_tile_size_allocated (self, w, alloc);
#line 948 "tile-view.c"
}


gboolean ui_widgets_tile_view_on_button_press (UIWidgetsTileView* self, GdkEventButton* event) {
	gboolean result = FALSE;
#line 198 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 198 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 200 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_object_set ((GtkWidget*) self, "has-focus", TRUE, NULL);
#line 202 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	ui_widgets_tile_view_clear_selection (self);
#line 962 "tile-view.c"
	{
		gint i = 0;
#line 204 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		i = 0;
#line 967 "tile-view.c"
		{
			gboolean _tmp0_ = FALSE;
#line 204 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp0_ = TRUE;
#line 204 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			while (TRUE) {
#line 974 "tile-view.c"
				gint _tmp2_ = 0;
				GList* _tmp3_ = NULL;
				guint _tmp4_ = 0U;
				UIWidgetsTile* t = NULL;
				GList* _tmp5_ = NULL;
				gint _tmp6_ = 0;
				gconstpointer _tmp7_ = NULL;
				GtkAllocation alloc = {0};
				UIWidgetsTile* _tmp8_ = NULL;
				GtkAllocation _tmp9_ = {0};
				cairo_region_t* region = NULL;
				GtkAllocation _tmp10_ = {0};
				cairo_rectangle_int_t _tmp11_ = {0};
				cairo_region_t* _tmp12_ = NULL;
				cairo_region_t* _tmp13_ = NULL;
				GdkEventButton* _tmp14_ = NULL;
				gdouble _tmp15_ = 0.0;
				GdkEventButton* _tmp16_ = NULL;
				gdouble _tmp17_ = 0.0;
				gboolean _tmp18_ = FALSE;
#line 204 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				if (!_tmp0_) {
#line 997 "tile-view.c"
					gint _tmp1_ = 0;
#line 204 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
					_tmp1_ = i;
#line 204 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
					i = _tmp1_ + 1;
#line 1003 "tile-view.c"
				}
#line 204 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp0_ = FALSE;
#line 204 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp2_ = i;
#line 204 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp3_ = self->priv->tiles;
#line 204 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp4_ = g_list_length (_tmp3_);
#line 204 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				if (!(((guint) _tmp2_) < _tmp4_)) {
#line 204 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
					break;
#line 1017 "tile-view.c"
				}
#line 206 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp5_ = self->priv->tiles;
#line 206 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp6_ = i;
#line 206 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp7_ = g_list_nth_data (_tmp5_, (guint) _tmp6_);
#line 206 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				t = (UIWidgetsTile*) _tmp7_;
#line 208 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp8_ = t;
#line 208 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				gtk_widget_get_allocation ((GtkWidget*) _tmp8_, &_tmp9_);
#line 208 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				alloc = _tmp9_;
#line 209 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp10_ = alloc;
#line 209 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp11_ = (cairo_rectangle_int_t) _tmp10_;
#line 209 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp12_ = cairo_region_create_rectangle (&_tmp11_);
#line 209 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				region = _tmp12_;
#line 210 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp13_ = region;
#line 210 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp14_ = event;
#line 210 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp15_ = _tmp14_->x;
#line 210 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp16_ = event;
#line 210 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp17_ = _tmp16_->y;
#line 210 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_tmp18_ = cairo_region_contains_point (_tmp13_, (gint) _tmp15_, (gint) _tmp17_);
#line 210 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				if (_tmp18_) {
#line 1055 "tile-view.c"
					gint _tmp19_ = 0;
#line 212 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
					_tmp19_ = i;
#line 212 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
					ui_widgets_tile_view_select (self, _tmp19_);
#line 213 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
					_cairo_region_destroy0 (region);
#line 213 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
					break;
#line 1065 "tile-view.c"
				}
#line 204 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
				_cairo_region_destroy0 (region);
#line 1069 "tile-view.c"
			}
		}
	}
#line 217 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	gtk_widget_queue_draw ((GtkWidget*) self);
#line 219 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	result = FALSE;
#line 219 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	return result;
#line 1079 "tile-view.c"
}


gboolean ui_widgets_tile_view_on_key_press (UIWidgetsTileView* self, GdkEventKey* event) {
	gboolean result = FALSE;
	gint index = 0;
	gint _tmp0_ = 0;
	GdkEventKey* _tmp1_ = NULL;
	guint _tmp2_ = 0U;
	gint _tmp5_ = 0;
	GList* _tmp6_ = NULL;
	guint _tmp7_ = 0U;
	gint _tmp8_ = 0;
	gint _tmp9_ = 0;
	gint _tmp10_ = 0;
#line 222 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 222 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 224 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp0_ = self->selected_index;
#line 224 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	index = _tmp0_;
#line 226 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp1_ = event;
#line 226 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp2_ = _tmp1_->keyval;
#line 226 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	switch (_tmp2_) {
#line 226 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		case GDK_KEY_Up:
#line 226 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		case GDK_KEY_KP_Up:
#line 226 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		case GDK_KEY_uparrow:
#line 1115 "tile-view.c"
		{
			gint _tmp3_ = 0;
#line 231 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp3_ = index;
#line 231 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			index = _tmp3_ - 1;
#line 232 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			break;
#line 1124 "tile-view.c"
		}
#line 226 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		case GDK_KEY_Down:
#line 226 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		case GDK_KEY_KP_Down:
#line 226 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		case GDK_KEY_downarrow:
#line 1132 "tile-view.c"
		{
			gint _tmp4_ = 0;
#line 236 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			_tmp4_ = index;
#line 236 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			index = _tmp4_ + 1;
#line 237 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
			break;
#line 1141 "tile-view.c"
		}
		default:
#line 226 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		break;
#line 1146 "tile-view.c"
	}
#line 240 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp5_ = index;
#line 240 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp6_ = self->priv->tiles;
#line 240 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp7_ = g_list_length (_tmp6_);
#line 240 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp8_ = CLAMP (_tmp5_, 0, ((gint) _tmp7_) - 1);
#line 240 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	index = _tmp8_;
#line 242 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp9_ = index;
#line 242 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp10_ = self->selected_index;
#line 242 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	if (_tmp9_ != _tmp10_) {
#line 1164 "tile-view.c"
		gint _tmp11_ = 0;
#line 244 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		ui_widgets_tile_view_clear_selection (self);
#line 245 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp11_ = index;
#line 245 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		ui_widgets_tile_view_select (self, _tmp11_);
#line 246 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		result = TRUE;
#line 246 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		return result;
#line 1176 "tile-view.c"
	}
#line 249 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	result = FALSE;
#line 249 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	return result;
#line 1182 "tile-view.c"
}


void ui_widgets_tile_view_select (UIWidgetsTileView* self, gint index) {
	gint _tmp0_ = 0;
	GList* _tmp1_ = NULL;
	guint _tmp2_ = 0U;
	gint _tmp3_ = 0;
	gboolean _tmp8_ = FALSE;
	GtkContainer* _tmp9_ = NULL;
#line 252 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_if_fail (self != NULL);
#line 254 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp0_ = index;
#line 254 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp1_ = self->priv->tiles;
#line 254 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp2_ = g_list_length (_tmp1_);
#line 254 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp3_ = _tmp0_;
#line 254 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	if ((0 <= _tmp3_) && (_tmp3_ < _tmp2_)) {
#line 1205 "tile-view.c"
		gint _tmp4_ = 0;
		GList* _tmp5_ = NULL;
		gint _tmp6_ = 0;
		gconstpointer _tmp7_ = NULL;
#line 256 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp4_ = index;
#line 256 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		self->selected_index = _tmp4_;
#line 257 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp5_ = self->priv->tiles;
#line 257 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp6_ = index;
#line 257 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp7_ = g_list_nth_data (_tmp5_, (guint) _tmp6_);
#line 257 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		ui_widgets_tile_set_selected ((UIWidgetsTile*) _tmp7_, TRUE);
#line 1222 "tile-view.c"
	} else {
#line 261 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		ui_widgets_tile_view_clear_selection (self);
#line 1226 "tile-view.c"
	}
#line 264 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp9_ = (GtkContainer*) gtk_widget_get_parent ((GtkWidget*) self);
#line 264 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	if (_tmp9_ != NULL) {
#line 1232 "tile-view.c"
		GtkContainer* _tmp10_ = NULL;
		gboolean _tmp11_ = FALSE;
#line 264 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp10_ = (GtkContainer*) gtk_widget_get_parent ((GtkWidget*) self);
#line 264 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp11_ = gtk_widget_get_realized ((GtkWidget*) _tmp10_);
#line 264 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp8_ = _tmp11_;
#line 1241 "tile-view.c"
	} else {
#line 264 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp8_ = FALSE;
#line 1245 "tile-view.c"
	}
#line 264 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	if (_tmp8_) {
#line 1249 "tile-view.c"
		GtkContainer* _tmp12_ = NULL;
#line 266 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		_tmp12_ = (GtkContainer*) gtk_widget_get_parent ((GtkWidget*) self);
#line 266 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		gtk_widget_queue_draw ((GtkWidget*) _tmp12_);
#line 1255 "tile-view.c"
	}
#line 269 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	gtk_widget_queue_resize ((GtkWidget*) self);
#line 1259 "tile-view.c"
}


gint ui_widgets_tile_view_get_icon_size (UIWidgetsTileView* self) {
	gint result;
	gint _tmp0_ = 0;
#line 31 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 31 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp0_ = self->priv->_icon_size;
#line 31 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	result = _tmp0_;
#line 31 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	return result;
#line 1274 "tile-view.c"
}


void ui_widgets_tile_view_set_icon_size (UIWidgetsTileView* self, gint value) {
	gint _tmp0_ = 0;
#line 31 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_return_if_fail (self != NULL);
#line 31 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp0_ = value;
#line 31 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	self->priv->_icon_size = _tmp0_;
#line 31 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_object_notify ((GObject *) self, "icon-size");
#line 1288 "tile-view.c"
}


static void ui_widgets_tile_view_class_init (UIWidgetsTileViewClass * klass) {
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	ui_widgets_tile_view_parent_class = g_type_class_peek_parent (klass);
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_type_class_add_private (klass, sizeof (UIWidgetsTileViewPrivate));
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	((UIWidgetsTileViewClass *) klass)->append_tile = ui_widgets_tile_view_real_append_tile;
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	((UIWidgetsTileViewClass *) klass)->remove_tile = ui_widgets_tile_view_real_remove_tile;
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	((UIWidgetsTileViewClass *) klass)->clear_selection = ui_widgets_tile_view_real_clear_selection;
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	((UIWidgetsTileViewClass *) klass)->get_current_tile = ui_widgets_tile_view_real_get_current_tile;
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	((GtkWidgetClass *) klass)->style_updated = ui_widgets_tile_view_real_style_updated;
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	((UIWidgetsTileViewClass *) klass)->on_tile_active_changed = ui_widgets_tile_view_real_on_tile_active_changed;
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	((UIWidgetsTileViewClass *) klass)->on_tile_size_allocated = ui_widgets_tile_view_real_on_tile_size_allocated;
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_ui_widgets_tile_view_get_property;
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_ui_widgets_tile_view_set_property;
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	G_OBJECT_CLASS (klass)->finalize = ui_widgets_tile_view_finalize;
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), UI_WIDGETS_TILE_VIEW_ICON_SIZE, g_param_spec_int ("icon-size", "icon-size", "icon-size", G_MININT, G_MAXINT, 48, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
#line 1319 "tile-view.c"
}


static void ui_widgets_tile_view_instance_init (UIWidgetsTileView * self) {
	GtkBox* _tmp0_ = NULL;
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	self->priv = UI_WIDGETS_TILE_VIEW_GET_PRIVATE (self);
#line 28 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	self->priv->tiles = NULL;
#line 29 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_tmp0_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
#line 29 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	g_object_ref_sink (_tmp0_);
#line 29 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	self->priv->box = _tmp0_;
#line 31 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	self->priv->_icon_size = 48;
#line 33 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	self->selected_index = -1;
#line 135 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	self->priv->changing_style = FALSE;
#line 1341 "tile-view.c"
}


static void ui_widgets_tile_view_finalize (GObject* obj) {
	UIWidgetsTileView * self;
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, UI_WIDGETS_TYPE_TILE_VIEW, UIWidgetsTileView);
#line 28 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	__g_list_free__g_object_unref0_0 (self->priv->tiles);
#line 29 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	_g_object_unref0 (self->priv->box);
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	G_OBJECT_CLASS (ui_widgets_tile_view_parent_class)->finalize (obj);
#line 1355 "tile-view.c"
}


GType ui_widgets_tile_view_get_type (void) {
	static volatile gsize ui_widgets_tile_view_type_id__volatile = 0;
	if (g_once_init_enter (&ui_widgets_tile_view_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (UIWidgetsTileViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ui_widgets_tile_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UIWidgetsTileView), 0, (GInstanceInitFunc) ui_widgets_tile_view_instance_init, NULL };
		GType ui_widgets_tile_view_type_id;
		ui_widgets_tile_view_type_id = g_type_register_static (gtk_event_box_get_type (), "UIWidgetsTileView", &g_define_type_info, 0);
		g_once_init_leave (&ui_widgets_tile_view_type_id__volatile, ui_widgets_tile_view_type_id);
	}
	return ui_widgets_tile_view_type_id__volatile;
}


static void _vala_ui_widgets_tile_view_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	UIWidgetsTileView * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, UI_WIDGETS_TYPE_TILE_VIEW, UIWidgetsTileView);
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	switch (property_id) {
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		case UI_WIDGETS_TILE_VIEW_ICON_SIZE:
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		g_value_set_int (value, ui_widgets_tile_view_get_icon_size (self));
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		break;
#line 1382 "tile-view.c"
		default:
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		break;
#line 1388 "tile-view.c"
	}
}


static void _vala_ui_widgets_tile_view_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	UIWidgetsTileView * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, UI_WIDGETS_TYPE_TILE_VIEW, UIWidgetsTileView);
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
	switch (property_id) {
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		case UI_WIDGETS_TILE_VIEW_ICON_SIZE:
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		ui_widgets_tile_view_set_icon_size (self, g_value_get_int (value));
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		break;
#line 1404 "tile-view.c"
		default:
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 26 "/home/mdeheij/projects/src/github.com/mdeheij/synapse/synapse-project/src/ui/tile-view/tile-view.vala"
		break;
#line 1410 "tile-view.c"
	}
}



